services:
  backend:
    depends_on:
      - mongo1
      - mongo2
      - mongo3

    build: ./backend
    container_name: nexus-backend

    ports:
      - "3000:3000"

    env_file:
      - ./backend/.env

    develop:
      watch:
        - path: ./backend/package.json
          action: rebuild

        - path: ./backend/package-lock.json
          action: rebuild

        - path: ./backend
          target: /app
          action: sync

  frontend:
    build: ./frontend
    container_name: nexus-frontend

    ports:
      - "5173:5173"

    depends_on:
      - backend

    env_file:
      - ./frontend/.env

    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild

        - path: ./frontend/package-lock.json
          action: rebuild

        - path: ./frontend
          target: /app
          action: sync


  mongo1:
    image: mongo
    container_name: mongo1
    hostname: mongo1
    ports:
      - "27017:27017"
    command: mongod --replSet rsBanco
    volumes:
      - mongo1_data:/data/db

  mongo2:
    image: mongo
    container_name: mongo2
    hostname: mongo2
    ports:
      - "27018:27017"
    command: mongod --replSet rsBanco
    volumes:
      - mongo2_data:/data/db

  mongo3:
    image: mongo
    container_name: mongo3
    hostname: mongo3
    ports:
      - "27019:27017"
    command: mongod --replSet rsBanco
    volumes:
      - mongo3_data:/data/db

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data: